#!/bin/bash

debug=false

#Décalaration des variables
dossierPoubelle="$HOME/poubelle"

recupererFichier=false
voirContenuPoubelle=false
viderPoubelle=false

fichiers=""

if echo $# | grep -x 0 1>/dev/null 2>&1
then
	echo "Utilisation :"
	echo "jeter [Options]... [Fichier]... "
	echo
	echo "Options : "
	echo "-r : Récupérer le(s) fichier(s)"
	echo "-l : Lister les fichiers dans la corbeille"
	echo "-v : Vider la corbeille"
fi

#On traite les paramètres
for i in `seq $#`
do
	if echo $1 | grep -x -e -r>/dev/null
	then
		recupererFichier=true
	elif echo $1 | grep -x -e -l>/dev/null
	then
		voirContenuPoubelle=true
	elif echo $1 | grep -x -e -v>/dev/null
	then
		viderPoubelle=true
	else
		fichiers="$1 $fichiers"
	fi

	if $debug
	then
		echo "Argument \$1 : " $1
	fi

	#Paramètre suivant !
	shift
done

#On creer la poubelle si elle existe pas !
mkdir -p $dossierPoubelle

#DEBUG
if $debug
then
	echo "Récupérer ce fichier : " $recupererFichier
	echo "Voir le contenu de la poubelle : " $voirContenuPoubelle
	echo "Vider la poubelle : " $viderPoubelle
	echo "Le(s) fichier(s) à mettre à la poubelle :" $fichiers
fi

#Mettre à la corbeille si on ne récupère pas de fichier
if ! $recupererFichier && echo $fichiers | grep -v -x "">/dev/null
then
	echo "Mise à la corbeille de : $fichiers"
	mv -n $fichiers $dossierPoubelle
fi

#Vider la poubelle
if $viderPoubelle
then
	echo "Vidage de la poubelle."
	rm -r $dossierPoubelle
fi

#Voir contenu de la poubelle
if $voirContenuPoubelle
then
	echo "Contenu de la poubelle : "
	ls -l $dossierPoubelle
fi

#Récupérer un fichier
if $recupererFichier && echo $fichiers | grep -v -x "">/dev/null
then
	echo "Récupération du/des fichier(s) : $fichiers"
	mv -n $dossierPoubelle/$fichiers .
fi
